apiVersion: apps/v1 
kind: StatefulSet
metadata:  
  name: mongodb  
  labels: 
    app: mongodb 
    tier: db
    project: roboshop 
spec: 
  serviceName: "mongodb"
  replicas: 1
  selector: 
    matchLabels: 
      app: mongodb 
      tier: db 
      project: roboshop 
  template:
    metadata: 
      labels: 
        app: mongodb 
        tier: db 
        project: roboshop 
    spec: 
      containers: 
      - name: mongodb 
        image: akarapunikhilchandra/mongodb:1.0.0 
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-dynamic-ebs"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1  # Corrected
kind: Service 
metadata: 
  name: nginx-stateless  
spec: 
  clusterIP: None 
  selector: 
    app: mongodb 
    tier: db 
    project: roboshop 
  ports: 
  - name: mongodb-port 
    protocol: TCP 
    port: 27017 
    targetPort: 27017
