apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop 
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: roboshop
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: "akarapunikhilchandra/mysql:{{ .Values.replicaset.imageVersion }}"
        envFrom:
        - configMapRef:
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes: 
      - name: mysql 
        PersistentVolumeClaim: 
          claimName: ebs-mysql-pvc 
 
