apiVersion: apps/v1 
kind: StatefulSet
metadata:  
  name: redis  
  namespace: roboshop 
  labels: 
    app: redis 
    tier: db
    project: roboshop 
spec: 
  serviceName: "redis"
  replicas: 1
  selector: 
    matchLabels: 
      app: redis 
      tier: db 
      project: roboshop 
  template:
    metadata: 
      labels: 
        app: redis 
        tier: db 
        project: roboshop 
    spec: 
      containers: 
      - name: redis 
        image: redis 
        volumeMounts:
        - name: redis
          mountPath: /data
      volumes: 
      - name: redis 
        persistentVolumeClaim: 
          claimName: "ebs-redis-pvc" 